import React from 'react';

function Home(props) {
    return (
        <div>
            <h2 style={{color:"red"}}>Home Component</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque dolorum itaque dolores autem assumenda error excepturi fugit quidem vitae eius iste voluptate soluta, perferendis et? Dolore ad ullam facilis natus autem eligendi doloremque, accusamus enim distinctio exercitationem dolorem nostrum placeat, facere reprehenderit nihil commodi repellat quas at id ratione. Esse minima quae id eos qui quaerat mollitia neque illum optio. Officia tempore exercitationem quia ut minus optio nesciunt animi tenetur nisi. Error, voluptatibus. Nihil error ex sequi minima eveniet. Veniam nihil qui similique, quam sit corporis quod voluptas labore reprehenderit quidem amet vero ratione eaque totam maxime, fugit suscipit laboriosam!</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores iste dignissimos adipisci recusandae aliquid at ab dolorum enim labore culpa, eos itaque delectus, voluptas neque quia accusantium, veritatis corrupti nobis tenetur! Corporis, ipsam! Quam optio possimus ipsum repudiandae autem. Magni ipsum incidunt voluptate porro animi tenetur soluta eveniet assumenda, inventore nemo hic earum veritatis iste! Consectetur sequi nam non consequatur inventore earum? Eum, laudantium? Ducimus dolor et ipsum voluptas fuga maxime provident esse quam id? Explicabo earum reprehenderit laboriosam. Ea dicta nulla, voluptatibus, totam accusantium vero velit, magni blanditiis quis distinctio fugiat excepturi necessitatibus fugit consectetur aut cupiditate laboriosam nostrum aliquam? Laborum, minus iure aliquam adipisci modi quasi repudiandae aperiam vel quae unde minima voluptatem saepe. Voluptates, dignissimos esse omnis quasi veniam perspiciatis nihil, modi aliquid officia inventore, vero et alias quibusdam! Architecto et officiis soluta veritatis cum corrupti! Perspiciatis fugit animi at, obcaecati a recusandae placeat nisi doloremque odio id accusamus voluptatum ipsum ducimus excepturi velit ut eum sunt assumenda et harum. Quos quaerat ipsa non, sequi ex ratione consectetur vero nihil necessitatibus consequuntur in voluptates omnis dolores. Deserunt officia cum, rerum aspernatur dicta qui, voluptatum culpa iste quibusdam delectus nemo soluta corrupti ea atque, ullam veritatis ipsum at amet. Illo, deleniti dolorum laborum quo nesciunt eaque minima nihil. Harum quam accusantium eaque, maiores quibusdam autem maxime consequuntur, dolorum ab tenetur, incidunt beatae facilis cupiditate non! Expedita ducimus repellat, totam aperiam incidunt explicabo, distinctio, quos alias facilis ipsum quae quod adipisci. Alias temporibus dolores illum ab est necessitatibus explicabo dicta ullam nobis totam veniam adipisci, dolor amet nulla vitae eligendi doloremque, numquam, culpa eius odit quam! Cupiditate architecto harum impedit atque nisi fugiat reprehenderit repellat veniam voluptas cumque consequatur maiores vero accusamus quod molestiae tempore tenetur non, quidem blanditiis excepturi ullam. Eos optio eligendi dicta fuga illo! Nobis, et.</p>
        </div>


    );
}

export default Home;